# managed by go/iml_to_build
java_import(
    name = "google-api-services-storage-v1-rev1-1.18.0-rc",
    jars = ["google-api-services-storage-v1-rev1-1.18.0-rc.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "google-api-services-testing-v1-revsnapshot-1.20.0",
    jars = ["google-api-services-testing-v1-revsnapshot-1.20.0.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "google-api-services-toolresults-v1beta3-rev20151013-1.20.0",
    jars = ["google-api-services-toolresults-v1beta3-rev20151013-1.20.0.jar"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "licenses",
    srcs = glob(["licenses/**"]),
    visibility = ["//visibility:public"],
)
