java_import(
    name = "uiautomatorviewer",
    jars = ["uiautomatorviewer.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "swt",
    jars = ["swt.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "licenses",
    srcs = glob(["licenses/**"]),
    visibility = ["//visibility:public"],
)
